name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"

      - name: Enable Android NDK 27
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "ndkVersion=27.0.12077973" >> android/local.properties
          sed -i 's/android {/android {\n    ndkVersion "27.0.12077973"/' android/app/build.gradle || true
          sed -i 's/android {/android {\n    ndkVersion = "27.0.12077973"/' android/app/build.gradle.kts || true

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EmoPDFReader-APK
          path: build/app/outputs/flutter-apk/app-release.apk
